# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: nsra
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 20
  cycle_time_error_threshold: 0.1
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Rev1
    - Rev2
    - Rev3
    - Rev4
    - Rev5
    - Rev6
    - Slider8
    - Slider9
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20
controller_list:
  - name: manipulator_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
      - Rev6
      - Slider8
      - Slider9
  
  - name: joint_position_controller
    action_ns: joint_group_position_controller
    default: True
    type: JointGroupPositionController
    joints:
      - Rev6
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5

  - name: gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    parallel: true
    joints:
      - Slider8
      - Slider9